name: Build and Publish Docker Image to GitHub Container Registry

on:
  release:
    types: [published]

# Request the required permissions
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx for advanced build features
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          # If you prefer to use a PAT, uncomment the following lines and
          # add a secret called GHCR_PAT in your repository settings:
          # username: kille250
          # password: ${{ secrets.GHCR_PAT }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Use the release tag for the image tag and optionally also tag as latest.
          tags: |
            ghcr.io/${{ github.repository_owner }}/discord-website:${{ github.event.release.tag_name }}
            ghcr.io/${{ github.repository_owner }}/discord-website:latest
